[[redirects]]
  from = "/accessibility-statement.html"
  to = "/accessibility-statement/"

[[redirects]]
  from = "/writing.html"
  to = "/writing/"

[[redirects]]
  from = "/speaking.html"
  to = "/speaking/"

[[redirects]]
  from = "/office-hours.html"
  to = "/office-hours/"

[[redirects]]
  from = "/colophon.html"
  to = "/colophon/"

[[redirects]]
  from = "/old-stuff.html"
  to = "/old-stuff/"

[[redirects]]
  from = "/writing/the-radium-craze.html"
  to = "/writing/the-radium-craze/"

[[redirects]]
  from = "/writing/a11y-is-web-accessibility.html"
  to = "/writing/a11y-is-web-accessibility/"

[[redirects]]
  from = "/writing/mug-handles.html"
  to = "/writing/mug-handles/"

[[redirects]]
  from = "/writing/how-to-not-make-a-resume-in-react.html"
  to = "/writing/how-to-not-make-a-resume-in-react/"

[[redirects]]
  from = "/writing/tech-metaphors.html"
  to = "/writing/tech-metaphors/"

[[redirects]]
  from = "/writing/its-all-disparate-its-all-connected.html"
  to = "/writing/its-all-disparate-its-all-connected/"

[[redirects]]
  from = "/writing/truths-about-digital-accessibility.html"
  to = "/writing/truths-about-digital-accessibility/"

[[redirects]]
  from = "/writing/2019-05-14-lighthouse.html"
  to = "/writing/2019-05-14-lighthouse/"

[[redirects]]
  from = "/writing/2019-03-05-fighting-uphill.html"
  to = "/writing/fighting-uphill/"
